#Service details: 
server:
  port: 8811
  error:
    include-stacktrace: never
#Data source: 
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: password
#JPA / Hibernate: 
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  application:
    name: USER-SERVICE

#Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


